### ISSUE TITLE
Amazon s3 sync fails silently

### ISSUE THREAD

**Issue by stack413** [sebastianfeldmann/phpbu#90] opened 2017-03-21 19:55 UTC
I've been testing out this framework and have run into issues getting the s3 sync to work. I'll run the command and it finishes without error, generating the local backup as expected. However, nothing gets uploaded to S3. My S3 logs seem to indicate that there was no attempt at all, and watching the console it looks like the sync step completes immediately after the check step – there should be a pause while the archive transmits, right?

I'm using using php 5.4, phpbu 4.0.3 (via composer) and aws-sdk-php 2.7 on CentOS 6.8. As far as I know the AWS side of things is set up correctly – the IAM user has full s3 permissions, the bucket doesn't have any weird policies, etc. 

A secondary issue is that the phpbu's logging doesn't seem to be creating/updating a log file like I've directed it to. I'm not sure if I've configured it wrong, or if I just haven't done anything that triggered a log write. 

Here's an (anonymized) copy of the configuration I'm using:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpbu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="http://schema.phpbu.de/4.0/phpbu.xsd">
  <log type="json" target="backup/logfile.json" />
  <backups>
    <backup>
      <!-- backup source -->
      <source type="mysqldump">
        <option name="databases" value="my_db"/>
        <option name="user" value="backup"/>
        <option name="password" value="[elided]"/>
        <option name="structureOnly" value="my_db.log"/>
        <option name="lockTables" value="true"/>
      </source>
      <!-- where should the backup be stored -->
      <target dirname="backup/mysql"
              filename="my_db-%Y%m%d-%H%i.sql"
              compress="bzip2"/>
      <sync type="amazons3">
        <option name="key" value="[elided]"/>
        <option name="secret" value="[elided]"/>
        <option name="bucket" value="my-bucket"/>
        <option name="region" value="us-east-2"/>
        <option name="path" value="/"/>
      </sync>
      <!-- check the created backup -->
      <check type="SizeMin" value="10M"/>
      <!-- cleanup the backup location
           as soon as all created backups exceed 500MB
           remove oldest backups -->
      <cleanup type="Capacity">
        <option name="size" value="500M"/>
      </cleanup>

    </backup>
  </backups>
</phpbu>
```

And here's an example of the command and output has be outputting:

```bash
backups@me [~/backup_test]# php vendor/phpbu/phpbu/phpbu --configuration=test.xml --debug --verbose --colors
phpbu 4.0.3

Runtime:       PHP 5.4.37
Configuration: ~/backup_test/test.xml
backup: [mysqldump] *******************************************************
(/usr/bin/mysqldump --user='backup' --password='[elided]' --lock-tables 'my_db' --no-data && /usr/bin/mysqldump --user='backup' --password='[elided]' --lock-tables 'my_db' --ignore-table='my_db.log' --skip-add-drop-table --no-create-db --no-create-info) | /usr/bin/bzip2 > ~/backup_test/backup/mysql/mesclub_forum-20170321-1212.sql.bz2
ok

check: [SizeMin] **********************************************************
checking: [10M] ok

sync: [amazons3] **********************************************************
```

Thanks for considering this.

**Comment by sebastianfeldmann** [comment] 2017-03-21 20:25
Strange, this works for me, and the file can be found in my S3 bucket
```xml
<sync type="amazons3">
        <option name="key" value="[elided]" />
        <option name="secret" value="[elided]" />
        <option name="bucket" value="phpbu" />
        <option name="region" value="eu-central-1" />
        <option name="path" value="/" />
</sync>
```

You can try to add some debug output by editing
`vendor/phpbu/phpbu/src/Backup/Sync/AmazonS3v3.php`

https://github.com/sebastianfeldmann/phpbu/blob/master/src/Backup/Sync/AmazonS3v3.php#L31-L52

For example with `$result->debug('some message');`

**Comment by stack413** [comment] 2017-03-21 20:46
Ok, well, it's good to know that I'm not doing anything obviously stupid. I'll try poking around with that debugging method and let you know if anything turns up, thank you.

**Comment by stack413** [comment] 2017-03-21 21:52
Ok, some investigation turns up at least part of the problem. For whatever reason, it was dying quietly when it tried to make the S3 client connection.  Updating how the client was initialized fixes the dying, although the upload is still not working because ???:

https://github.com/stack413/phpbu/blob/035ee557cfb8c7d7b738c1d309b65d43686c220e/src/Backup/Sync/AmazonS3v3.php#L33

**Comment by sebastianfeldmann** [comment] 2017-03-23 08:56
Can you paste the code for the changed initialisation here? Maybe I can have a look into the issue from here.

**Comment by sebastianfeldmann** [comment] 2017-03-26 21:40
Any new on this?

**Comment by basz** [comment] 2017-04-17 20:53
hello! i think i have the same issue. bucket exists, no files are uploaded.

**Comment by sebastianfeldmann** [comment] 2017-04-18 06:09
I'm still trying to reproduce this behavior.
Can you provide some more details?
- phpbu version
- PHP version
- Backup file size
- PHAR or Composer installed
- If composer installed AWS Version 2 or 3

Cheers, Sebastian

**Comment by sebastianfeldmann** [comment] 2017-09-19 08:45
I'll close this issue because at the moment there is no way for me to reproduce this.

If you still have this error, please provide some more information about your setup.

**Closed by sebastianfeldmann** 2017-09-19 08:45 UTC
Labels: bug

**Comment by nitsan-technologies** [comment] 2020-07-11 10:17
Hey @sebastianfeldmann 

We faced this same issue, you know what's a strange thing "If backup file's size is below ~2MB then Amazon S3 sync does not work", We have tested it several times and concluded it. Hope you will able to resolve it ;)

Cheers,
Sanjay
